site_name: TCC-Metano – Documentação
site_url: https://gabriela-frajtag.github.io/TCC-Metano/
repo_url: https://github.com/gabriela-frajtag/TCC-Metano
theme:
  name: readthedocs
  language: pt-BR
  palette:
    scheme: default
    primary: teal
    accent: amber
nav:
  - Visão geral: index.md
  - Scripts: scripts.md
  - Análises:
    - Geral: analises.md
    - Boltz: boltzina.md
    - Dinâmica Molecular: dinamica.md
    - PropKa: propka.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gabriela-frajtag/TCC-Metano
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition

